const { num, POSITION_MAP, mapPlayerStatus, execBatch } = require('../lib/helpers');

async function syncPlayers(conn, elements, teamsById, seasonId) {
  const rows = elements.map((p) => {
    const team = teamsById.get(p.team);
    return [
      p.id,
      `${p.first_name || ''} ${p.second_name || ''}`.trim(),
      team ? team.name : '',
      p.team,
      POSITION_MAP[p.element_type] || 'MID',
      p.web_name,
      mapPlayerStatus(p.status),
      p.news || '',
      num(p.now_cost) / 10,
      num(p.total_points),
      num(p.form),
      num(p.minutes),
      num(p.goals_scored),
      num(p.assists),
      num(p.clean_sheets),
      num(p.saves),
      num(p.yellow_cards),
      num(p.red_cards),
      num(p.transfers_out),
      num(p.transfers_out_event),
      num(p.transfers_in),
      num(p.transfers_in_event),
      num(p.selected_by_percent),
      num(p.cost_change_event),
      num(p.cost_change_event_fall),
      num(p.cost_change_start),
      num(p.cost_change_start_fall),
      num(p.dreamteam_count),
      num(p.points_per_game),
      num(p.value_form),
      num(p.value_season),
      num(p.influence),
      num(p.creativity),
      num(p.threat),
      num(p.ict_index),
      p.influence_rank,
      p.influence_rank_type,
      p.creativity_rank,
      p.creativity_rank_type,
      p.threat_rank,
      p.threat_rank_type,
      p.ict_index_rank,
      p.ict_index_rank_type,
      p.corners_and_indirect_freekicks_order,
      p.direct_freekicks_order,
      p.penalties_order,
      num(p.expected_goals_per_90),
      num(p.saves_per_90),
      num(p.expected_assists_per_90),
      num(p.expected_goal_involvements_per_90),
      num(p.expected_goals_conceded_per_90),
      num(p.goals_conceded_per_90),
      p.now_cost_rank,
      p.now_cost_rank_type,
      p.form_rank,
      p.form_rank_type,
      p.points_per_game_rank,
      p.points_per_game_rank_type,
      p.selected_rank,
      p.selected_rank_type,
      num(p.starts_per_90),
      num(p.clean_sheets_per_90),
      seasonId,
    ];
  });

  await execBatch(
    conn,
    `INSERT INTO fpl_hub_player_data (
      player_id, player_name, team_name, team_id, pos, web_name, status, news,
      price, points, form, minutes, goals, assists, cs, saves, yc, rc,
      tout, tout_event, tin, tin_event, selected_by_percent,
      cost_change_event, cost_change_event_fall, cost_change_start, cost_change_start_fall,
      dreamteam_count, ppg, value_form, value_season,
      influence, creativity, threat, ict_index,
      influence_rank, influence_rank_type, creativity_rank, creativity_rank_type,
      threat_rank, threat_rank_type, ict_index_rank, ict_index_rank_type,
      corners_and_indirect_freekicks_order, direct_freekicks_order, penalties_order,
      xg_per_90, saves_per_90, xa_per_90, xgi_per_90, xgc_90, gc_per_90,
      now_cost_rank, now_cost_rank_type, form_rank, form_rank_type,
      points_per_game_rank, points_per_game_rank_type, selected_rank, selected_rank_type,
      starts_per_90, cs_per_90, pyfy
    )`,
    `ON DUPLICATE KEY UPDATE
      player_name=VALUES(player_name), team_name=VALUES(team_name), team_id=VALUES(team_id),
      pos=VALUES(pos), web_name=VALUES(web_name), status=VALUES(status), news=VALUES(news),
      price=VALUES(price), points=VALUES(points), form=VALUES(form), minutes=VALUES(minutes),
      goals=VALUES(goals), assists=VALUES(assists), cs=VALUES(cs), saves=VALUES(saves),
      yc=VALUES(yc), rc=VALUES(rc), tout=VALUES(tout), tout_event=VALUES(tout_event),
      tin=VALUES(tin), tin_event=VALUES(tin_event), selected_by_percent=VALUES(selected_by_percent),
      cost_change_event=VALUES(cost_change_event), cost_change_event_fall=VALUES(cost_change_event_fall),
      cost_change_start=VALUES(cost_change_start), cost_change_start_fall=VALUES(cost_change_start_fall),
      dreamteam_count=VALUES(dreamteam_count), ppg=VALUES(ppg), value_form=VALUES(value_form),
      value_season=VALUES(value_season), influence=VALUES(influence), creativity=VALUES(creativity),
      threat=VALUES(threat), ict_index=VALUES(ict_index),
      influence_rank=VALUES(influence_rank), influence_rank_type=VALUES(influence_rank_type),
      creativity_rank=VALUES(creativity_rank), creativity_rank_type=VALUES(creativity_rank_type),
      threat_rank=VALUES(threat_rank), threat_rank_type=VALUES(threat_rank_type),
      ict_index_rank=VALUES(ict_index_rank), ict_index_rank_type=VALUES(ict_index_rank_type),
      corners_and_indirect_freekicks_order=VALUES(corners_and_indirect_freekicks_order),
      direct_freekicks_order=VALUES(direct_freekicks_order), penalties_order=VALUES(penalties_order),
      xg_per_90=VALUES(xg_per_90), saves_per_90=VALUES(saves_per_90), xa_per_90=VALUES(xa_per_90),
      xgi_per_90=VALUES(xgi_per_90), xgc_90=VALUES(xgc_90), gc_per_90=VALUES(gc_per_90),
      now_cost_rank=VALUES(now_cost_rank), now_cost_rank_type=VALUES(now_cost_rank_type),
      form_rank=VALUES(form_rank), form_rank_type=VALUES(form_rank_type),
      points_per_game_rank=VALUES(points_per_game_rank),
      points_per_game_rank_type=VALUES(points_per_game_rank_type),
      selected_rank=VALUES(selected_rank), selected_rank_type=VALUES(selected_rank_type),
      starts_per_90=VALUES(starts_per_90), cs_per_90=VALUES(cs_per_90), pyfy=VALUES(pyfy)`,
    rows
  );
  return rows.length;
}

module.exports = { syncPlayers };
