-- Source API: GET /api/bootstrap-static/ → elements[]
CREATE TABLE IF NOT EXISTS fpl_hub_player_data (
  player_id INT UNSIGNED NOT NULL COMMENT 'Official FPL element id',
  player_name VARCHAR(150) NOT NULL,
  team_name VARCHAR(100) NOT NULL,
  team_id INT UNSIGNED NOT NULL,
  pos ENUM('GKP','DEF','MID','FOR') NOT NULL,
  web_name VARCHAR(100) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'Available',
  news TEXT NULL,
  price DECIMAL(5,1) NOT NULL DEFAULT 0.0,
  points INT NOT NULL DEFAULT 0,
  form DECIMAL(6,2) NOT NULL DEFAULT 0,
  minutes INT NOT NULL DEFAULT 0,
  goals INT NOT NULL DEFAULT 0,
  assists INT NOT NULL DEFAULT 0,
  cs INT NOT NULL DEFAULT 0,
  saves INT NOT NULL DEFAULT 0,
  yc INT NOT NULL DEFAULT 0,
  rc INT NOT NULL DEFAULT 0,
  tout INT NOT NULL DEFAULT 0,
  tout_event INT NOT NULL DEFAULT 0,
  tin INT NOT NULL DEFAULT 0,
  tin_event INT NOT NULL DEFAULT 0,
  selected_by_percent DECIMAL(6,2) NOT NULL DEFAULT 0,
  cost_change_event INT NOT NULL DEFAULT 0,
  cost_change_event_fall INT NOT NULL DEFAULT 0,
  cost_change_start INT NOT NULL DEFAULT 0,
  cost_change_start_fall INT NOT NULL DEFAULT 0,
  dreamteam_count INT NOT NULL DEFAULT 0,
  ppg DECIMAL(6,2) NOT NULL DEFAULT 0,
  value_form DECIMAL(8,2) NOT NULL DEFAULT 0,
  value_season DECIMAL(8,2) NOT NULL DEFAULT 0,
  influence DECIMAL(8,2) NOT NULL DEFAULT 0,
  creativity DECIMAL(8,2) NOT NULL DEFAULT 0,
  threat DECIMAL(8,2) NOT NULL DEFAULT 0,
  ict_index DECIMAL(8,2) NOT NULL DEFAULT 0,
  influence_rank INT NULL,
  influence_rank_type INT NULL,
  creativity_rank INT NULL,
  creativity_rank_type INT NULL,
  threat_rank INT NULL,
  threat_rank_type INT NULL,
  ict_index_rank INT NULL,
  ict_index_rank_type INT NULL,
  corners_and_indirect_freekicks_order INT NULL,
  direct_freekicks_order INT NULL,
  penalties_order INT NULL,
  xg_per_90 DECIMAL(8,3) NOT NULL DEFAULT 0,
  saves_per_90 DECIMAL(8,3) NOT NULL DEFAULT 0,
  xa_per_90 DECIMAL(8,3) NOT NULL DEFAULT 0,
  xgi_per_90 DECIMAL(8,3) NOT NULL DEFAULT 0,
  xgc_90 DECIMAL(8,3) NOT NULL DEFAULT 0,
  gc_per_90 DECIMAL(8,3) NOT NULL DEFAULT 0,
  now_cost_rank INT NULL,
  now_cost_rank_type INT NULL,
  form_rank INT NULL,
  form_rank_type INT NULL,
  points_per_game_rank INT NULL,
  points_per_game_rank_type INT NULL,
  selected_rank INT NULL,
  selected_rank_type INT NULL,
  starts_per_90 DECIMAL(8,3) NOT NULL DEFAULT 0,
  cs_per_90 DECIMAL(8,3) NOT NULL DEFAULT 0,
  pyfy VARCHAR(16) NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (player_id),
  KEY idx_player_team (team_id),
  KEY idx_player_pos (pos),
  KEY idx_player_web_name (web_name),
  CONSTRAINT fk_player_team FOREIGN KEY (team_id) REFERENCES fpl_hub_team_data (team_id)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
