-- Source API: GET /api/bootstrap-static/ → events[]
CREATE TABLE IF NOT EXISTS fpl_hub_gw_data (
  gw_id INT UNSIGNED NOT NULL COMMENT 'Official FPL event id',
  gw VARCHAR(32) NOT NULL,
  season_id VARCHAR(16) NOT NULL DEFAULT '',
  gw_deadline DATETIME NULL,
  status VARCHAR(32) NOT NULL DEFAULT '',
  average_score INT NULL,
  highest_score INT NULL,
  event_is_pre TINYINT(1) NOT NULL DEFAULT 0,
  event_is_cur TINYINT(1) NOT NULL DEFAULT 0,
  event_is_next TINYINT(1) NOT NULL DEFAULT 0,
  event_can_enter TINYINT(1) NOT NULL DEFAULT 0,
  event_can_manage TINYINT(1) NOT NULL DEFAULT 0,
  bboost_count INT NOT NULL DEFAULT 0,
  freehit_count INT NOT NULL DEFAULT 0,
  wildcard_count INT NOT NULL DEFAULT 0,
  xc3_count INT NOT NULL DEFAULT 0,
  most_selected VARCHAR(100) NULL,
  most_ti VARCHAR(100) NULL,
  highest_player VARCHAR(100) NULL,
  hp_score INT NULL,
  most_c VARCHAR(100) NULL,
  most_vc VARCHAR(100) NULL,
  transfers_made INT NULL,
  finished TINYINT(1) NOT NULL DEFAULT 0,
  pyfy VARCHAR(16) NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (gw_id),
  KEY idx_gw_current (event_is_cur)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
